# Generated by Django 5.0.3 on 2024-09-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(blank=True, max_length=50, null=True)),
                ('mesik', models.BooleanField(default=False)),
                ('direcrotName', models.CharField(blank=True, max_length=50, null=True)),
                ('medibName', models.CharField(blank=True, max_length=50, null=True)),
                ('bureaueNo', models.CharField(blank=True, max_length=50, null=True)),
                ('dateS', models.CharField(blank=True, max_length=50, null=True)),
                ('fullName', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('disability', models.CharField(blank=True, max_length=50, null=True)),
                ('itemType', models.CharField(blank=True, max_length=50, null=True)),
                ('systemType', models.CharField(blank=True, max_length=50, null=True)),
                ('reportedProblem', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
