# Generated by Django 5.0.3 on 2024-09-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(blank=True, max_length=50, null=True)),
                ('reportId', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('happenedProblem', models.CharField(blank=True, max_length=50, null=True)),
                ('sole', models.CharField(blank=True, max_length=50, null=True)),
                ('startDate', models.CharField(blank=True, max_length=50, null=True)),
                ('endDate', models.CharField(blank=True, max_length=50, null=True)),
                ('isProblemFixed', models.CharField(blank=True, max_length=50, null=True)),
                ('reasonProblemNotFixed', models.CharField(blank=True, max_length=50, null=True)),
                ('itTechName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
