# Generated by Django 5.0.3 on 2024-09-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial_23'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='reportId',
            field=models.IntegerField(default=1),
        ),
    ]
